const SELECTED_NANO_NEEDLING_DURATION = "SELECTED_NANO_NEEDLING_DURATION";

const ACTION_SELECTED_NANO_NEEDLING_DURATION = (duration) => {
  return {
    type: SELECTED_NANO_NEEDLING_DURATION,
    duration,
  };
};

export default ACTION_SELECTED_NANO_NEEDLING_DURATION;
