const SELECTED_NANO_NEEDLING_DURATION_RESET = "SELECTED_NANO_NEEDLING_DURATION_RESET";

const ACTION_SELECTED_NANO_NEEDLING_DURATION_RESET = () => {
  return {
      type: SELECTED_NANO_NEEDLING_DURATION_RESET,
  };
};

export default ACTION_SELECTED_NANO_NEEDLING_DURATION_RESET;
